#!/usr/bin/env sh
#*******************************************************************************
# Copyright (c) 2018 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    sed 's#nginx:.*#nginx:x:'$(id -u)':0:Linux User,,,:/var/cache/nginx:/sbin/nologin#' /etc/passwd > /tmp/passwd
    # cannot do inplace nor mv as we don't have write permissions in /etc
    cat /tmp/passwd > /etc/passwd
    rm /tmp/passwd
  fi
fi
exec "$@"